[package]
name = "rio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
name = "rio"
crate-type = ["rlib", "staticlib"]

[dependencies]
ffk.workspace = true
lazy_static.workspace = true
dashmap.workspace = true

[build-dependencies]
cbindgen.workspace = true
